/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareYourStoryRouteImport } from './routes/share-your-story'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindRouteImport } from './routes/find'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RedeemedCodeRouteImport } from './routes/redeemed.$code'
import { Route as ReceiptCodeRouteImport } from './routes/receipt.$code'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminMailingRouteImport } from './routes/admin.mailing'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as AdminCopyRouteImport } from './routes/admin.copy'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ShareYourStoryRoute = ShareYourStoryRouteImport.update({
  id: '/share-your-story',
  path: '/share-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RedeemedCodeRoute = RedeemedCodeRouteImport.update({
  id: '/redeemed/$code',
  path: '/redeemed/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptCodeRoute = ReceiptCodeRouteImport.update({
  id: '/receipt/$code',
  path: '/receipt/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailingRoute = AdminMailingRouteImport.update({
  id: '/mailing',
  path: '/mailing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopyRoute = AdminCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/copy': typeof AdminCopyRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/mailing': typeof AdminMailingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/receipt/$code': typeof ReceiptCodeRoute
  '/redeemed/$code': typeof RedeemedCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/copy': typeof AdminCopyRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/mailing': typeof AdminMailingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/receipt/$code': typeof ReceiptCodeRoute
  '/redeemed/$code': typeof RedeemedCodeRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/copy': typeof AdminCopyRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/mailing': typeof AdminMailingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/receipt/$code': typeof ReceiptCodeRoute
  '/redeemed/$code': typeof RedeemedCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/find'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/redeem'
    | '/share-your-story'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/copy'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/mailing'
    | '/admin/testimonials'
    | '/receipt/$code'
    | '/redeemed/$code'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/find'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/redeem'
    | '/share-your-story'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/copy'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/mailing'
    | '/admin/testimonials'
    | '/receipt/$code'
    | '/redeemed/$code'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/find'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/redeem'
    | '/share-your-story'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/audit'
    | '/admin/copy'
    | '/admin/errors'
    | '/admin/faqs'
    | '/admin/mailing'
    | '/admin/testimonials'
    | '/receipt/$code'
    | '/redeemed/$code'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FaqRoute: typeof FaqRoute
  FindRoute: typeof FindRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  RedeemRoute: typeof RedeemRoute
  ShareYourStoryRoute: typeof ShareYourStoryRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ReceiptCodeRoute: typeof ReceiptCodeRoute
  RedeemedCodeRoute: typeof RedeemedCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-your-story': {
      id: '/share-your-story'
      path: '/share-your-story'
      fullPath: '/share-your-story'
      preLoaderRoute: typeof ShareYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/redeemed/$code': {
      id: '/redeemed/$code'
      path: '/redeemed/$code'
      fullPath: '/redeemed/$code'
      preLoaderRoute: typeof RedeemedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$code': {
      id: '/receipt/$code'
      path: '/receipt/$code'
      fullPath: '/receipt/$code'
      preLoaderRoute: typeof ReceiptCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mailing': {
      id: '/admin/mailing'
      path: '/mailing'
      fullPath: '/admin/mailing'
      preLoaderRoute: typeof AdminMailingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copy': {
      id: '/admin/copy'
      path: '/copy'
      fullPath: '/admin/copy'
      preLoaderRoute: typeof AdminCopyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCopyRoute: typeof AdminCopyRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminMailingRoute: typeof AdminMailingRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCopyRoute: AdminCopyRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminMailingRoute: AdminMailingRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FaqRoute: FaqRoute,
  FindRoute: FindRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  RedeemRoute: RedeemRoute,
  ShareYourStoryRoute: ShareYourStoryRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ReceiptCodeRoute: ReceiptCodeRoute,
  RedeemedCodeRoute: RedeemedCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
